
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QStackedWidget,
    QStatusBar, QTextEdit, QWidget)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(483, 366)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 60, 371, 41))
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 120, 481, 241))
        self.username_question = QWidget()
        self.username_question.setObjectName(u"username_question")
        self.new_pass_FP = QLineEdit(self.username_question)
        self.new_pass_FP.setObjectName(u"new_pass_FP")
        self.new_pass_FP.setGeometry(QRect(150, 60, 301, 21))
        self.new_pass_FP.setEchoMode(QLineEdit.EchoMode.Password)
        self.confirm_new_pass_FP = QLineEdit(self.username_question)
        self.confirm_new_pass_FP.setObjectName(u"confirm_new_pass_FP")
        self.confirm_new_pass_FP.setGeometry(QRect(150, 93, 301, 21))
        self.confirm_new_pass_FP.setEchoMode(QLineEdit.EchoMode.Password)
        self.label_3 = QLabel(self.username_question)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(38, 62, 91, 20))
        self.label_4 = QLabel(self.username_question)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(18, 93, 111, 20))
        self.submit_register = QPushButton(self.username_question)
        self.submit_register.setObjectName(u"submit_register")
        self.submit_register.setGeometry(QRect(340, 160, 111, 24))
        self.FP_cancel2 = QPushButton(self.username_question)
        self.FP_cancel2.setObjectName(u"FP_cancel2")
        self.FP_cancel2.setGeometry(QRect(340, 190, 111, 24))
        self.stackedWidget.addWidget(self.username_question)
        self.verify_new = QWidget()
        self.verify_new.setObjectName(u"verify_new")
        self.label_5 = QLabel(self.verify_new)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(17, 70, 111, 20))
        self.label_6 = QLabel(self.verify_new)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(17, 98, 111, 41))
        self.label_2 = QLabel(self.verify_new)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(68, 40, 61, 20))
        self.answer_FP = QTextEdit(self.verify_new)
        self.answer_FP.setObjectName(u"answer_FP")
        self.answer_FP.setGeometry(QRect(147, 103, 301, 31))
        self.special_question_FP = QComboBox(self.verify_new)
        self.special_question_FP.addItem("")
        self.special_question_FP.addItem("")
        self.special_question_FP.addItem("")
        self.special_question_FP.addItem("")
        self.special_question_FP.addItem("")
        self.special_question_FP.addItem("")
        self.special_question_FP.addItem("")
        self.special_question_FP.addItem("")
        self.special_question_FP.addItem("")
        self.special_question_FP.setObjectName(u"special_question_FP")
        self.special_question_FP.setGeometry(QRect(147, 70, 303, 21))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.special_question_FP.sizePolicy().hasHeightForWidth())
        self.special_question_FP.setSizePolicy(sizePolicy)
        self.special_question_FP.setMaximumSize(QSize(16777215, 16777214))
        self.special_question_FP.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.username_FP = QLineEdit(self.verify_new)
        self.username_FP.setObjectName(u"username_FP")
        self.username_FP.setGeometry(QRect(147, 38, 301, 21))
        self.confirm_FP = QPushButton(self.verify_new)
        self.confirm_FP.setObjectName(u"confirm_FP")
        self.confirm_FP.setGeometry(QRect(330, 160, 111, 24))
        self.cancel_FP = QPushButton(self.verify_new)
        self.cancel_FP.setObjectName(u"cancel_FP")
        self.cancel_FP.setGeometry(QRect(330, 190, 111, 24))
        self.stackedWidget.addWidget(self.verify_new)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700;\">Forgot Password</span></p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\">New Password</p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\">Confirm Password</p></body></html>", None))
        self.submit_register.setText(QCoreApplication.translate("MainWindow", u"Submit Credentials", None))
        self.FP_cancel2.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\">Special Question</p></body></html>", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\">Answer to<br/>Special Question</p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\">Username</p></body></html>", None))
        self.special_question_FP.setItemText(0, QCoreApplication.translate("MainWindow", u"Select a question", None))
        self.special_question_FP.setItemText(1, QCoreApplication.translate("MainWindow", u"Who was your childhood hero?", None))
        self.special_question_FP.setItemText(2, QCoreApplication.translate("MainWindow", u"What was the name of your first pet?", None))
        self.special_question_FP.setItemText(3, QCoreApplication.translate("MainWindow", u"What is your mother's maiden name?", None))
        self.special_question_FP.setItemText(4, QCoreApplication.translate("MainWindow", u"What was the name of your first school?", None))
        self.special_question_FP.setItemText(5, QCoreApplication.translate("MainWindow", u"What is your favorite book?", None))
        self.special_question_FP.setItemText(6, QCoreApplication.translate("MainWindow", u"What is your favorite movie?", None))
        self.special_question_FP.setItemText(7, QCoreApplication.translate("MainWindow", u"What was your dream job as a child?", None))
        self.special_question_FP.setItemText(8, QCoreApplication.translate("MainWindow", u"What is the name of the town where you were born?", None))

        self.confirm_FP.setText(QCoreApplication.translate("MainWindow", u"Continue", None))
        self.cancel_FP.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
    # retranslateUi

