
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCalendarWidget, QCheckBox, QDateEdit,
    QFrame, QHBoxLayout, QHeaderView, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QSpinBox, QStackedWidget, QStatusBar, QTableView,
    QTableWidget, QTableWidgetItem, QTextEdit, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(908, 457)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.logo_wannabe = QLabel(self.centralwidget)
        self.logo_wannabe.setObjectName(u"logo_wannabe")
        self.logo_wannabe.setGeometry(QRect(20, 30, 181, 31))
        font = QFont()
        font.setFamilies([u"Segoe UI Black"])
        font.setPointSize(14)
        font.setBold(True)
        self.logo_wannabe.setFont(font)
        self.logo_wannabe.setTextFormat(Qt.TextFormat.AutoText)
        self.menu_label = QLabel(self.centralwidget)
        self.menu_label.setObjectName(u"menu_label")
        self.menu_label.setGeometry(QRect(20, 70, 181, 31))
        self.menu_label.setFont(font)
        self.menu_label.setTextFormat(Qt.TextFormat.AutoText)
        self.search_label = QLabel(self.centralwidget)
        self.search_label.setObjectName(u"search_label")
        self.search_label.setGeometry(QRect(241, 20, 51, 51))
        self.search_label.setFont(font)
        self.search_label.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.search_label.setTextFormat(Qt.TextFormat.AutoText)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(220, 20, 20, 631))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.search_bar = QLineEdit(self.centralwidget)
        self.search_bar.setObjectName(u"search_bar")
        self.search_bar.setGeometry(QRect(300, 30, 251, 31))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(9)
        font1.setBold(False)
        font1.setItalic(False)
        self.search_bar.setFont(font1)
        self.search_bar.setStyleSheet(u"font: 9pt \"Segoe UI\";")
        self.username_label = QLabel(self.centralwidget)
        self.username_label.setObjectName(u"username_label")
        self.username_label.setGeometry(QRect(730, 29, 141, 21))
        self.username_label.setFont(font)
        self.username_label.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.username_label.setTextFormat(Qt.TextFormat.AutoText)
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(240, 80, 661, 516))
        self.dashBoard = QWidget()
        self.dashBoard.setObjectName(u"dashBoard")
        self.welcome_label = QLabel(self.dashBoard)
        self.welcome_label.setObjectName(u"welcome_label")
        self.welcome_label.setGeometry(QRect(10, 10, 351, 41))
        self.welcome_label.setFont(font)
        self.welcome_label.setTextFormat(Qt.TextFormat.AutoText)
        self.horizontalLayoutWidget_5 = QWidget(self.dashBoard)
        self.horizontalLayoutWidget_5.setObjectName(u"horizontalLayoutWidget_5")
        self.horizontalLayoutWidget_5.setGeometry(QRect(10, 70, 241, 31))
        self.horizontalLayout_10 = QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.quick_raw = QPushButton(self.horizontalLayoutWidget_5)
        self.quick_raw.setObjectName(u"quick_raw")

        self.horizontalLayout_10.addWidget(self.quick_raw)

        self.quick_stock = QPushButton(self.horizontalLayoutWidget_5)
        self.quick_stock.setObjectName(u"quick_stock")

        self.horizontalLayout_10.addWidget(self.quick_stock)

        self.quickie_add = QLabel(self.dashBoard)
        self.quickie_add.setObjectName(u"quickie_add")
        self.quickie_add.setGeometry(QRect(20, 50, 91, 16))
        self.quickie_add.setFont(font)
        self.quickie_add.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.quickie_add.setTextFormat(Qt.TextFormat.AutoText)
        self.task_abel = QLabel(self.dashBoard)
        self.task_abel.setObjectName(u"task_abel")
        self.task_abel.setGeometry(QRect(20, 110, 91, 16))
        self.task_abel.setFont(font)
        self.task_abel.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.task_abel.setTextFormat(Qt.TextFormat.AutoText)
        self.horizontalLayoutWidget_6 = QWidget(self.dashBoard)
        self.horizontalLayoutWidget_6.setObjectName(u"horizontalLayoutWidget_6")
        self.horizontalLayoutWidget_6.setGeometry(QRect(10, 130, 501, 81))
        self.horizontalLayout_11 = QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20 = QVBoxLayout()
        self.verticalLayout_20.setObjectName(u"verticalLayout_20")
        self.checkBox_5 = QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_5.setObjectName(u"checkBox_5")

        self.verticalLayout_20.addWidget(self.checkBox_5)

        self.checkBox_36 = QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_36.setObjectName(u"checkBox_36")

        self.verticalLayout_20.addWidget(self.checkBox_36)

        self.checkBox_37 = QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_37.setObjectName(u"checkBox_37")

        self.verticalLayout_20.addWidget(self.checkBox_37)


        self.horizontalLayout_11.addLayout(self.verticalLayout_20)

        self.verticalLayout_21 = QVBoxLayout()
        self.verticalLayout_21.setObjectName(u"verticalLayout_21")
        self.checkBox_38 = QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_38.setObjectName(u"checkBox_38")

        self.verticalLayout_21.addWidget(self.checkBox_38)

        self.checkBox_39 = QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_39.setObjectName(u"checkBox_39")

        self.verticalLayout_21.addWidget(self.checkBox_39)

        self.checkBox_40 = QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_40.setObjectName(u"checkBox_40")

        self.verticalLayout_21.addWidget(self.checkBox_40)


        self.horizontalLayout_11.addLayout(self.verticalLayout_21)

        self.verticalLayout_22 = QVBoxLayout()
        self.verticalLayout_22.setObjectName(u"verticalLayout_22")
        self.checkBox_41 = QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_41.setObjectName(u"checkBox_41")

        self.verticalLayout_22.addWidget(self.checkBox_41)

        self.checkBox_42 = QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_42.setObjectName(u"checkBox_42")

        self.verticalLayout_22.addWidget(self.checkBox_42)

        self.checkBox_43 = QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_43.setObjectName(u"checkBox_43")

        self.verticalLayout_22.addWidget(self.checkBox_43)


        self.horizontalLayout_11.addLayout(self.verticalLayout_22)

        self.label_22 = QLabel(self.dashBoard)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 220, 121, 16))
        self.label_22.setFont(font)
        self.label_22.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.label_22.setTextFormat(Qt.TextFormat.AutoText)
        self.line_5 = QFrame(self.dashBoard)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(510, 10, 20, 371))
        self.line_5.setFrameShape(QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_23 = QLabel(self.dashBoard)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(530, 20, 91, 16))
        self.label_23.setFont(font)
        self.label_23.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.label_23.setTextFormat(Qt.TextFormat.AutoText)
        self.label = QLabel(self.dashBoard)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(530, 40, 131, 16))
        self.logout_button = QPushButton(self.dashBoard)
        self.logout_button.setObjectName(u"logout_button")
        self.logout_button.setGeometry(QRect(543, 329, 111, 24))
        self.dashboard_label = QLabel(self.dashBoard)
        self.dashboard_label.setObjectName(u"dashboard_label")
        self.dashboard_label.setGeometry(QRect(430, 10, 91, 41))
        self.dashboard_label.setFont(font)
        self.dashboard_label.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.dashboard_label.setTextFormat(Qt.TextFormat.AutoText)
        self.prod_table = QTableView(self.dashBoard)
        self.prod_table.setObjectName(u"prod_table")
        self.prod_table.setGeometry(QRect(10, 240, 501, 111))
        self.add_account = QPushButton(self.dashBoard)
        self.add_account.setObjectName(u"add_account")
        self.add_account.setGeometry(QRect(543, 300, 111, 24))
        self.stackedWidget.addWidget(self.dashBoard)
        self.Inventory = QWidget()
        self.Inventory.setObjectName(u"Inventory")
        self.product_inventory_table = QTableWidget(self.Inventory)
        self.product_inventory_table.setObjectName(u"product_inventory_table")
        self.product_inventory_table.setGeometry(QRect(50, 60, 571, 121))
        self.welcome_label_2 = QLabel(self.Inventory)
        self.welcome_label_2.setObjectName(u"welcome_label_2")
        self.welcome_label_2.setGeometry(QRect(60, 20, 191, 31))
        self.welcome_label_2.setFont(font)
        self.welcome_label_2.setTextFormat(Qt.TextFormat.AutoText)
        self.raw_inventory_table = QTableWidget(self.Inventory)
        self.raw_inventory_table.setObjectName(u"raw_inventory_table")
        self.raw_inventory_table.setGeometry(QRect(50, 230, 571, 121))
        self.welcome_label_4 = QLabel(self.Inventory)
        self.welcome_label_4.setObjectName(u"welcome_label_4")
        self.welcome_label_4.setGeometry(QRect(60, 190, 181, 31))
        self.welcome_label_4.setFont(font)
        self.welcome_label_4.setTextFormat(Qt.TextFormat.AutoText)
        self.add_product_button = QPushButton(self.Inventory)
        self.add_product_button.setObjectName(u"add_product_button")
        self.add_product_button.setGeometry(QRect(254, 25, 71, 24))
        self.add_inventory_button = QPushButton(self.Inventory)
        self.add_inventory_button.setObjectName(u"add_inventory_button")
        self.add_inventory_button.setGeometry(QRect(254, 195, 71, 24))
        self.stackedWidget.addWidget(self.Inventory)
        self.inventory_add_product = QWidget()
        self.inventory_add_product.setObjectName(u"inventory_add_product")
        self.cancel_add_invProduct = QPushButton(self.inventory_add_product)
        self.cancel_add_invProduct.setObjectName(u"cancel_add_invProduct")
        self.cancel_add_invProduct.setGeometry(QRect(412, 300, 70, 24))
        self.save_add_invProduct = QPushButton(self.inventory_add_product)
        self.save_add_invProduct.setObjectName(u"save_add_invProduct")
        self.save_add_invProduct.setGeometry(QRect(340, 300, 70, 24))
        self.label_45 = QLabel(self.inventory_add_product)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(120, 210, 121, 21))
        self.label_47 = QLabel(self.inventory_add_product)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(130, 130, 111, 21))
        self.add_inventory_product = QSpinBox(self.inventory_add_product)
        self.add_inventory_product.setObjectName(u"add_inventory_product")
        self.add_inventory_product.setGeometry(QRect(270, 127, 211, 22))
        self.add_inventory_product.setMaximum(999999)
        self.label_48 = QLabel(self.inventory_add_product)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(150, 171, 91, 21))
        self.inventory_product_cost = QSpinBox(self.inventory_add_product)
        self.inventory_product_cost.setObjectName(u"inventory_product_cost")
        self.inventory_product_cost.setGeometry(QRect(270, 207, 211, 22))
        self.inventory_product_cost.setMaximum(999999)
        self.inventory_bag_type = QLineEdit(self.inventory_add_product)
        self.inventory_bag_type.setObjectName(u"inventory_bag_type")
        self.inventory_bag_type.setGeometry(QRect(270, 90, 211, 21))
        self.label_49 = QLabel(self.inventory_add_product)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(0, 37, 651, 31))
        self.label_50 = QLabel(self.inventory_add_product)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(160, 90, 81, 21))
        self.add_inventory_defective = QSpinBox(self.inventory_add_product)
        self.add_inventory_defective.setObjectName(u"add_inventory_defective")
        self.add_inventory_defective.setGeometry(QRect(270, 168, 211, 22))
        self.add_inventory_defective.setMaximum(999999)
        self.label_46 = QLabel(self.inventory_add_product)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(120, 250, 121, 21))
        self.inventory_active_product = QSpinBox(self.inventory_add_product)
        self.inventory_active_product.setObjectName(u"inventory_active_product")
        self.inventory_active_product.setGeometry(QRect(270, 248, 211, 22))
        self.inventory_active_product.setMaximum(999999)
        self.stackedWidget.addWidget(self.inventory_add_product)
        self.inventory_edit_product = QWidget()
        self.inventory_edit_product.setObjectName(u"inventory_edit_product")
        self.update_products = QPushButton(self.inventory_edit_product)
        self.update_products.setObjectName(u"update_products")
        self.update_products.setGeometry(QRect(260, 290, 70, 24))
        self.Edit_inventory_product_2 = QSpinBox(self.inventory_edit_product)
        self.Edit_inventory_product_2.setObjectName(u"Edit_inventory_product_2")
        self.Edit_inventory_product_2.setGeometry(QRect(270, 117, 211, 22))
        self.Edit_inventory_product_2.setMaximum(999999)
        self.cancel_update_product = QPushButton(self.inventory_edit_product)
        self.cancel_update_product.setObjectName(u"cancel_update_product")
        self.cancel_update_product.setGeometry(QRect(412, 290, 70, 24))
        self.label_51 = QLabel(self.inventory_edit_product)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(120, 240, 121, 21))
        self.Edit_inventory_bag_type = QLineEdit(self.inventory_edit_product)
        self.Edit_inventory_bag_type.setObjectName(u"Edit_inventory_bag_type")
        self.Edit_inventory_bag_type.setGeometry(QRect(270, 80, 211, 21))
        self.label_55 = QLabel(self.inventory_edit_product)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(120, 200, 121, 21))
        self.edit_inventory_defective_2 = QSpinBox(self.inventory_edit_product)
        self.edit_inventory_defective_2.setObjectName(u"edit_inventory_defective_2")
        self.edit_inventory_defective_2.setGeometry(QRect(270, 158, 211, 22))
        self.edit_inventory_defective_2.setMaximum(999999)
        self.label_53 = QLabel(self.inventory_edit_product)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(130, 120, 111, 21))
        self.edit_product_cost_2 = QSpinBox(self.inventory_edit_product)
        self.edit_product_cost_2.setObjectName(u"edit_product_cost_2")
        self.edit_product_cost_2.setGeometry(QRect(270, 197, 211, 22))
        self.edit_product_cost_2.setMaximum(999999)
        self.label_56 = QLabel(self.inventory_edit_product)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(160, 80, 81, 21))
        self.edit_inventory_active_product_2 = QSpinBox(self.inventory_edit_product)
        self.edit_inventory_active_product_2.setObjectName(u"edit_inventory_active_product_2")
        self.edit_inventory_active_product_2.setGeometry(QRect(270, 238, 211, 22))
        self.edit_inventory_active_product_2.setMaximum(999999)
        self.label_54 = QLabel(self.inventory_edit_product)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(0, 27, 651, 31))
        self.label_52 = QLabel(self.inventory_edit_product)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(150, 161, 91, 21))
        self.Archive_finished_product = QPushButton(self.inventory_edit_product)
        self.Archive_finished_product.setObjectName(u"Archive_finished_product")
        self.Archive_finished_product.setGeometry(QRect(337, 290, 70, 24))
        self.stackedWidget.addWidget(self.inventory_edit_product)
        self.inventory_add_raw = QWidget()
        self.inventory_add_raw.setObjectName(u"inventory_add_raw")
        self.add_inventory_Materiel = QLineEdit(self.inventory_add_raw)
        self.add_inventory_Materiel.setObjectName(u"add_inventory_Materiel")
        self.add_inventory_Materiel.setGeometry(QRect(270, 103, 211, 21))
        self.add_safety_stock = QSpinBox(self.inventory_add_raw)
        self.add_safety_stock.setObjectName(u"add_safety_stock")
        self.add_safety_stock.setGeometry(QRect(270, 223, 211, 22))
        self.add_safety_stock.setMaximum(999999)
        self.add_material_cost = QSpinBox(self.inventory_add_raw)
        self.add_material_cost.setObjectName(u"add_material_cost")
        self.add_material_cost.setGeometry(QRect(270, 163, 211, 22))
        self.add_material_cost.setMaximum(999999)
        self.label_65 = QLabel(self.inventory_add_raw)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(160, 103, 101, 21))
        self.add_material_supplier = QLineEdit(self.inventory_add_raw)
        self.add_material_supplier.setObjectName(u"add_material_supplier")
        self.add_material_supplier.setGeometry(QRect(270, 253, 211, 21))
        self.add_material_type = QLineEdit(self.inventory_add_raw)
        self.add_material_type.setObjectName(u"add_material_type")
        self.add_material_type.setGeometry(QRect(270, 133, 211, 21))
        self.label_67 = QLabel(self.inventory_add_raw)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(110, 223, 151, 21))
        self.label_68 = QLabel(self.inventory_add_raw)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(110, 252, 151, 21))
        self.save_add_raw = QPushButton(self.inventory_add_raw)
        self.save_add_raw.setObjectName(u"save_add_raw")
        self.save_add_raw.setGeometry(QRect(350, 293, 70, 24))
        self.label_72 = QLabel(self.inventory_add_raw)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(10, 50, 651, 31))
        self.label_69 = QLabel(self.inventory_add_raw)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(140, 163, 121, 21))
        self.add_material_stock = QSpinBox(self.inventory_add_raw)
        self.add_material_stock.setObjectName(u"add_material_stock")
        self.add_material_stock.setGeometry(QRect(270, 193, 211, 22))
        self.add_material_stock.setMaximum(999999)
        self.cancel_add_raw = QPushButton(self.inventory_add_raw)
        self.cancel_add_raw.setObjectName(u"cancel_add_raw")
        self.cancel_add_raw.setGeometry(QRect(422, 293, 70, 24))
        self.label_71 = QLabel(self.inventory_add_raw)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(140, 193, 121, 21))
        self.label_70 = QLabel(self.inventory_add_raw)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(150, 133, 111, 21))
        self.stackedWidget.addWidget(self.inventory_add_raw)
        self.inventory_edit_raw = QWidget()
        self.inventory_edit_raw.setObjectName(u"inventory_edit_raw")
        self.label_60 = QLabel(self.inventory_edit_raw)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(160, 103, 101, 21))
        self.edit_material_stock = QSpinBox(self.inventory_edit_raw)
        self.edit_material_stock.setObjectName(u"edit_material_stock")
        self.edit_material_stock.setGeometry(QRect(270, 193, 211, 22))
        self.edit_material_stock.setMaximum(999999)
        self.cancel_edit_raw = QPushButton(self.inventory_edit_raw)
        self.cancel_edit_raw.setObjectName(u"cancel_edit_raw")
        self.cancel_edit_raw.setGeometry(QRect(422, 293, 70, 24))
        self.archive_raw = QPushButton(self.inventory_edit_raw)
        self.archive_raw.setObjectName(u"archive_raw")
        self.archive_raw.setGeometry(QRect(347, 293, 70, 24))
        self.update_edit_raw = QPushButton(self.inventory_edit_raw)
        self.update_edit_raw.setObjectName(u"update_edit_raw")
        self.update_edit_raw.setGeometry(QRect(270, 293, 70, 24))
        self.edit_material_cost = QSpinBox(self.inventory_edit_raw)
        self.edit_material_cost.setObjectName(u"edit_material_cost")
        self.edit_material_cost.setGeometry(QRect(270, 163, 211, 22))
        self.edit_material_cost.setMaximum(999999)
        self.label_58 = QLabel(self.inventory_edit_raw)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(140, 163, 121, 21))
        self.label_59 = QLabel(self.inventory_edit_raw)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(150, 133, 111, 21))
        self.label_57 = QLabel(self.inventory_edit_raw)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(140, 193, 121, 21))
        self.label_61 = QLabel(self.inventory_edit_raw)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(10, 50, 651, 31))
        self.Edit_inventory_Materiel = QLineEdit(self.inventory_edit_raw)
        self.Edit_inventory_Materiel.setObjectName(u"Edit_inventory_Materiel")
        self.Edit_inventory_Materiel.setGeometry(QRect(270, 103, 211, 21))
        self.label_63 = QLabel(self.inventory_edit_raw)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(110, 223, 151, 21))
        self.Edit_material_type = QLineEdit(self.inventory_edit_raw)
        self.Edit_material_type.setObjectName(u"Edit_material_type")
        self.Edit_material_type.setGeometry(QRect(270, 133, 211, 21))
        self.edit_safety_stock = QSpinBox(self.inventory_edit_raw)
        self.edit_safety_stock.setObjectName(u"edit_safety_stock")
        self.edit_safety_stock.setGeometry(QRect(270, 223, 211, 22))
        self.edit_safety_stock.setMaximum(999999)
        self.label_64 = QLabel(self.inventory_edit_raw)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(110, 252, 151, 21))
        self.edit_material_supplier = QLineEdit(self.inventory_edit_raw)
        self.edit_material_supplier.setObjectName(u"edit_material_supplier")
        self.edit_material_supplier.setGeometry(QRect(270, 253, 211, 21))
        self.stackedWidget.addWidget(self.inventory_edit_raw)
        self.transac = QWidget()
        self.transac.setObjectName(u"transac")
        self.table_transac = QTableView(self.transac)
        self.table_transac.setObjectName(u"table_transac")
        self.table_transac.setEnabled(False)
        self.table_transac.setGeometry(QRect(0, 70, 661, 281))
        self.table_transac.horizontalHeader().setStretchLastSection(True)
        self.label_75 = QLabel(self.transac)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(10, 30, 631, 31))
        self.stackedWidget.addWidget(self.transac)
        self.help = QWidget()
        self.help.setObjectName(u"help")
        self.label_30 = QLabel(self.help)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(50, 99, 581, 211))
        font2 = QFont()
        font2.setFamilies([u"Poppins Light"])
        self.label_30.setFont(font2)
        self.label_31 = QLabel(self.help)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(50, 50, 381, 61))
        font3 = QFont()
        font3.setFamilies([u"Poppins ExtraBold"])
        font3.setPointSize(33)
        self.label_31.setFont(font3)
        self.pushButton = QPushButton(self.help)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(50, 300, 75, 24))
        self.stackedWidget.addWidget(self.help)
        self.maintenance = QWidget()
        self.maintenance.setObjectName(u"maintenance")
        self.maintenance_label = QLabel(self.maintenance)
        self.maintenance_label.setObjectName(u"maintenance_label")
        self.maintenance_label.setGeometry(QRect(90, 50, 361, 61))
        self.maintenance_label.setFont(font3)
        self.version_label = QLabel(self.maintenance)
        self.version_label.setObjectName(u"version_label")
        self.version_label.setGeometry(QRect(90, 110, 121, 61))
        self.version_label.setFont(font2)
        self.update_button = QPushButton(self.maintenance)
        self.update_button.setObjectName(u"update_button")
        self.update_button.setEnabled(False)
        self.update_button.setGeometry(QRect(90, 180, 75, 24))
        self.backup_button = QPushButton(self.maintenance)
        self.backup_button.setObjectName(u"backup_button")
        self.backup_button.setGeometry(QRect(90, 250, 75, 24))
        self.restore_button = QPushButton(self.maintenance)
        self.restore_button.setObjectName(u"restore_button")
        self.restore_button.setGeometry(QRect(90, 280, 75, 24))
        self.textEdit = QTextEdit(self.maintenance)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(230, 171, 171, 141))
        self.label_128 = QLabel(self.maintenance)
        self.label_128.setObjectName(u"label_128")
        self.label_128.setGeometry(QRect(230, 142, 131, 21))
        self.stackedWidget.addWidget(self.maintenance)
        self.prod = QWidget()
        self.prod.setObjectName(u"prod")
        self.welcome_label_3 = QLabel(self.prod)
        self.welcome_label_3.setObjectName(u"welcome_label_3")
        self.welcome_label_3.setGeometry(QRect(60, 20, 351, 31))
        self.welcome_label_3.setFont(font)
        self.welcome_label_3.setTextFormat(Qt.TextFormat.AutoText)
        self.product_table = QTableWidget(self.prod)
        self.product_table.setObjectName(u"product_table")
        self.product_table.setGeometry(QRect(50, 50, 571, 271))
        self.add_order_button = QPushButton(self.prod)
        self.add_order_button.setObjectName(u"add_order_button")
        self.add_order_button.setGeometry(QRect(540, 330, 75, 24))
        self.stackedWidget.addWidget(self.prod)
        self.prod_add = QWidget()
        self.prod_add.setObjectName(u"prod_add")
        self.order_quantity_spinBox = QSpinBox(self.prod_add)
        self.order_quantity_spinBox.setObjectName(u"order_quantity_spinBox")
        self.order_quantity_spinBox.setGeometry(QRect(50, 180, 211, 22))
        self.order_quantity_spinBox.setMaximum(999999)
        self.label_3 = QLabel(self.prod_add)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 60, 81, 21))
        self.client_name_entry = QLineEdit(self.prod_add)
        self.client_name_entry.setObjectName(u"client_name_entry")
        self.client_name_entry.setGeometry(QRect(50, 80, 211, 21))
        self.label_4 = QLabel(self.prod_add)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(50, 110, 81, 21))
        self.bag_type_entry = QLineEdit(self.prod_add)
        self.bag_type_entry.setObjectName(u"bag_type_entry")
        self.bag_type_entry.setGeometry(QRect(50, 130, 211, 21))
        self.label_9 = QLabel(self.prod_add)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(50, 160, 91, 21))
        self.label_10 = QLabel(self.prod_add)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(50, 210, 91, 21))
        self.order_deadline_dateEdit = QDateEdit(self.prod_add)
        self.order_deadline_dateEdit.setObjectName(u"order_deadline_dateEdit")
        self.order_deadline_dateEdit.setGeometry(QRect(50, 230, 211, 22))
        self.label_11 = QLabel(self.prod_add)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(340, 40, 81, 21))
        self.add_order_notes = QTextEdit(self.prod_add)
        self.add_order_notes.setObjectName(u"add_order_notes")
        self.add_order_notes.setGeometry(QRect(340, 60, 281, 251))
        self.label_12 = QLabel(self.prod_add)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(50, 260, 121, 21))
        self.order_priority_spinBox = QSpinBox(self.prod_add)
        self.order_priority_spinBox.setObjectName(u"order_priority_spinBox")
        self.order_priority_spinBox.setGeometry(QRect(50, 280, 211, 22))
        self.order_priority_spinBox.setMaximum(999999)
        self.cancel_add_order = QPushButton(self.prod_add)
        self.cancel_add_order.setObjectName(u"cancel_add_order")
        self.cancel_add_order.setGeometry(QRect(540, 330, 75, 24))
        self.save_add_order = QPushButton(self.prod_add)
        self.save_add_order.setObjectName(u"save_add_order")
        self.save_add_order.setGeometry(QRect(460, 330, 75, 24))
        self.label_13 = QLabel(self.prod_add)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(50, 20, 141, 31))
        self.stackedWidget.addWidget(self.prod_add)
        self.prod_edit = QWidget()
        self.prod_edit.setObjectName(u"prod_edit")
        self.edit_cancel_button = QPushButton(self.prod_edit)
        self.edit_cancel_button.setObjectName(u"edit_cancel_button")
        self.edit_cancel_button.setGeometry(QRect(540, 330, 75, 24))
        self.edit_save_button = QPushButton(self.prod_edit)
        self.edit_save_button.setObjectName(u"edit_save_button")
        self.edit_save_button.setGeometry(QRect(390, 330, 75, 24))
        self.label_38 = QLabel(self.prod_edit)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(50, 260, 121, 21))
        self.edit_order_notes = QTextEdit(self.prod_edit)
        self.edit_order_notes.setObjectName(u"edit_order_notes")
        self.edit_order_notes.setGeometry(QRect(340, 60, 281, 251))
        self.label_39 = QLabel(self.prod_edit)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(50, 60, 81, 21))
        self.label_40 = QLabel(self.prod_edit)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(50, 160, 91, 21))
        self.edit_order_deadline = QDateEdit(self.prod_edit)
        self.edit_order_deadline.setObjectName(u"edit_order_deadline")
        self.edit_order_deadline.setGeometry(QRect(50, 230, 211, 22))
        self.edit_order_quantity = QSpinBox(self.prod_edit)
        self.edit_order_quantity.setObjectName(u"edit_order_quantity")
        self.edit_order_quantity.setGeometry(QRect(50, 180, 211, 22))
        self.edit_order_quantity.setMaximum(999999)
        self.label_41 = QLabel(self.prod_edit)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(50, 210, 91, 21))
        self.edit_order_priority = QSpinBox(self.prod_edit)
        self.edit_order_priority.setObjectName(u"edit_order_priority")
        self.edit_order_priority.setGeometry(QRect(50, 280, 211, 22))
        self.edit_order_priority.setMaximum(999999)
        self.edit_client_name = QLineEdit(self.prod_edit)
        self.edit_client_name.setObjectName(u"edit_client_name")
        self.edit_client_name.setGeometry(QRect(50, 80, 211, 21))
        self.label_42 = QLabel(self.prod_edit)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(340, 40, 81, 21))
        self.edit_bag_type = QLineEdit(self.prod_edit)
        self.edit_bag_type.setObjectName(u"edit_bag_type")
        self.edit_bag_type.setGeometry(QRect(50, 130, 211, 21))
        self.label_43 = QLabel(self.prod_edit)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(50, 20, 141, 31))
        self.label_44 = QLabel(self.prod_edit)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(50, 110, 81, 21))
        self.void_order = QPushButton(self.prod_edit)
        self.void_order.setObjectName(u"void_order")
        self.void_order.setGeometry(QRect(465, 330, 75, 24))
        self.stackedWidget.addWidget(self.prod_edit)
        self.sched = QWidget()
        self.sched.setObjectName(u"sched")
        self.calendarWidget = QCalendarWidget(self.sched)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(0, 20, 651, 301))
        self.daily_calendar = QPushButton(self.sched)
        self.daily_calendar.setObjectName(u"daily_calendar")
        self.daily_calendar.setGeometry(QRect(570, 330, 75, 24))
        self.weekly_calendar = QPushButton(self.sched)
        self.weekly_calendar.setObjectName(u"weekly_calendar")
        self.weekly_calendar.setGeometry(QRect(490, 330, 75, 24))
        self.stackedWidget.addWidget(self.sched)
        self.sched_week = QWidget()
        self.sched_week.setObjectName(u"sched_week")
        self.label_73 = QLabel(self.sched_week)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(10, 30, 631, 31))
        self.weekly_table = QTableView(self.sched_week)
        self.weekly_table.setObjectName(u"weekly_table")
        self.weekly_table.setEnabled(False)
        self.weekly_table.setGeometry(QRect(0, 70, 661, 241))
        self.weekly_table.horizontalHeader().setStretchLastSection(True)
        self.return_calendar = QPushButton(self.sched_week)
        self.return_calendar.setObjectName(u"return_calendar")
        self.return_calendar.setGeometry(QRect(580, 330, 75, 24))
        self.edit_weekly = QPushButton(self.sched_week)
        self.edit_weekly.setObjectName(u"edit_weekly")
        self.edit_weekly.setGeometry(QRect(420, 330, 75, 24))
        self.save_weekly = QPushButton(self.sched_week)
        self.save_weekly.setObjectName(u"save_weekly")
        self.save_weekly.setEnabled(False)
        self.save_weekly.setGeometry(QRect(500, 330, 75, 24))
        self.stackedWidget.addWidget(self.sched_week)
        self.scheddaily = QWidget()
        self.scheddaily.setObjectName(u"scheddaily")
        self.label_74 = QLabel(self.scheddaily)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(10, 20, 631, 31))
        self.return_calendar_2 = QPushButton(self.scheddaily)
        self.return_calendar_2.setObjectName(u"return_calendar_2")
        self.return_calendar_2.setGeometry(QRect(580, 320, 75, 24))
        self.daily_table = QTableView(self.scheddaily)
        self.daily_table.setObjectName(u"daily_table")
        self.daily_table.setEnabled(True)
        self.daily_table.setGeometry(QRect(0, 60, 661, 241))
        self.daily_table.horizontalHeader().setStretchLastSection(True)
        self.save_daily = QPushButton(self.scheddaily)
        self.save_daily.setObjectName(u"save_daily")
        self.save_daily.setEnabled(False)
        self.save_daily.setGeometry(QRect(500, 320, 75, 24))
        self.edit_daily = QPushButton(self.scheddaily)
        self.edit_daily.setObjectName(u"edit_daily")
        self.edit_daily.setGeometry(QRect(420, 320, 75, 24))
        self.stackedWidget.addWidget(self.scheddaily)
        self.about = QWidget()
        self.about.setObjectName(u"about")
        self.label_2 = QLabel(self.about)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(80, 80, 401, 61))
        self.label_2.setFont(font3)
        self.label_29 = QLabel(self.about)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(80, 130, 501, 161))
        self.label_29.setFont(font2)
        self.stackedWidget.addWidget(self.about)
        self.reports = QWidget()
        self.reports.setObjectName(u"reports")
        self.maintenance_label_2 = QLabel(self.reports)
        self.maintenance_label_2.setObjectName(u"maintenance_label_2")
        self.maintenance_label_2.setGeometry(QRect(80, 50, 361, 61))
        self.maintenance_label_2.setFont(font3)
        self.layoutWidget = QWidget(self.reports)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(80, 130, 361, 91))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.prod_report_btn = QPushButton(self.layoutWidget)
        self.prod_report_btn.setObjectName(u"prod_report_btn")

        self.verticalLayout_2.addWidget(self.prod_report_btn)

        self.inventory_report_btn = QPushButton(self.layoutWidget)
        self.inventory_report_btn.setObjectName(u"inventory_report_btn")

        self.verticalLayout_2.addWidget(self.inventory_report_btn)


        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.stocks_report_btn = QPushButton(self.layoutWidget)
        self.stocks_report_btn.setObjectName(u"stocks_report_btn")

        self.verticalLayout_4.addWidget(self.stocks_report_btn)

        self.sales_report_btn = QPushButton(self.layoutWidget)
        self.sales_report_btn.setObjectName(u"sales_report_btn")

        self.verticalLayout_4.addWidget(self.sales_report_btn)


        self.horizontalLayout.addLayout(self.verticalLayout_4)

        self.stackedWidget.addWidget(self.reports)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(240, 70, 651, 20))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.layoutWidget1 = QWidget(self.centralwidget)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(20, 100, 191, 331))
        self.verticalLayout = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.dash_button = QPushButton(self.layoutWidget1)
        self.dash_button.setObjectName(u"dash_button")
        self.dash_button.setFlat(True)

        self.verticalLayout.addWidget(self.dash_button)

        self.prod_button = QPushButton(self.layoutWidget1)
        self.prod_button.setObjectName(u"prod_button")
        self.prod_button.setFlat(True)

        self.verticalLayout.addWidget(self.prod_button)

        self.sched_button = QPushButton(self.layoutWidget1)
        self.sched_button.setObjectName(u"sched_button")
        self.sched_button.setFlat(True)

        self.verticalLayout.addWidget(self.sched_button)

        self.invent_button = QPushButton(self.layoutWidget1)
        self.invent_button.setObjectName(u"invent_button")
        self.invent_button.setFlat(True)

        self.verticalLayout.addWidget(self.invent_button)

        self.rep_button = QPushButton(self.layoutWidget1)
        self.rep_button.setObjectName(u"rep_button")
        self.rep_button.setFlat(True)

        self.verticalLayout.addWidget(self.rep_button)

        self.transac_button = QPushButton(self.layoutWidget1)
        self.transac_button.setObjectName(u"transac_button")
        self.transac_button.setFlat(True)

        self.verticalLayout.addWidget(self.transac_button)

        self.help_button = QPushButton(self.layoutWidget1)
        self.help_button.setObjectName(u"help_button")
        self.help_button.setFlat(True)

        self.verticalLayout.addWidget(self.help_button)

        self.about_button = QPushButton(self.layoutWidget1)
        self.about_button.setObjectName(u"about_button")
        self.about_button.setFlat(True)

        self.verticalLayout.addWidget(self.about_button)

        self.maintenance_button = QPushButton(self.layoutWidget1)
        self.maintenance_button.setObjectName(u"maintenance_button")
        self.maintenance_button.setFlat(True)

        self.verticalLayout.addWidget(self.maintenance_button)

        self.username_id = QLabel(self.centralwidget)
        self.username_id.setObjectName(u"username_id")
        self.username_id.setGeometry(QRect(820, 49, 51, 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(5)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.logo_wannabe.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">Rexie Maris Bags</span></p></body></html>", None))
        self.menu_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:8pt; font-weight:400;\">Menu Bar</span></p></body></html>", None))
        self.search_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-size:9pt; font-weight:400; color:#ffffff;\">Search</span></p></body></html>", None))
        self.search_bar.setText("")
        self.username_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-style:italic;\">Maris Pascual</span></p></body></html>", None))
        self.welcome_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-style:italic;\">Dashboard</span></p></body></html>", None))
        self.quick_raw.setText(QCoreApplication.translate("MainWindow", u"Add Raw Material", None))
        self.quick_stock.setText(QCoreApplication.translate("MainWindow", u"Add Bag Product", None))
        self.quickie_add.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:8pt; font-weight:400; color:#ffffff;\">Quick Add</span></p></body></html>", None))
        self.task_abel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:8pt; font-weight:400; color:#ffffff;\">Tasks</span></p></body></html>", None))
        self.checkBox_5.setText(QCoreApplication.translate("MainWindow", u"Task 1", None))
        self.checkBox_36.setText(QCoreApplication.translate("MainWindow", u"Task 2", None))
        self.checkBox_37.setText(QCoreApplication.translate("MainWindow", u"Task 3", None))
        self.checkBox_38.setText(QCoreApplication.translate("MainWindow", u"Task 4", None))
        self.checkBox_39.setText(QCoreApplication.translate("MainWindow", u"Task 5", None))
        self.checkBox_40.setText(QCoreApplication.translate("MainWindow", u"Task 6", None))
        self.checkBox_41.setText(QCoreApplication.translate("MainWindow", u"Task 7", None))
        self.checkBox_42.setText(QCoreApplication.translate("MainWindow", u"Task 8", None))
        self.checkBox_43.setText(QCoreApplication.translate("MainWindow", u"Task 9", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:8pt; font-weight:400; color:#ffffff;\">Upcoming Deadlines</span></p></body></html>", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:8pt; font-weight:400; color:#ffffff;\">History</span></p></body></html>", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:6pt;\">Maris Pascual Added a raw material</span></p></body></html>", None))
        self.logout_button.setText(QCoreApplication.translate("MainWindow", u"Logout", None))
        self.dashboard_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:9pt; font-weight:400; color:#ffffff;\">Dashboard</span></p></body></html>", None))
        self.add_account.setText(QCoreApplication.translate("MainWindow", u"Add an Account", None))
        self.welcome_label_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-style:italic;\">Finish Product Inventory</span></p></body></html>", None))
        self.welcome_label_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-style:italic;\">Raw Material Inventory</span></p></body></html>", None))
        self.add_product_button.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.add_inventory_button.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.cancel_add_invProduct.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.save_add_invProduct.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Product Cost</span></p><p align=\"right\"><br/></p></body></html>", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Quantity</span></p><p align=\"right\"><br/></p></body></html>", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">No. of Defectives</span></p><p align=\"right\"><br/></p></body></html>", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:700;\">ADD FINISHED PRODUCT</span></p></body></html>", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Bag Type</span></p></body></html>", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">No. of Active</span></p><p align=\"right\"><br/></p></body></html>", None))
        self.update_products.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.cancel_update_product.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">No. of Active</span></p><p align=\"right\"><br/></p></body></html>", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Product Cost</span></p><p align=\"right\"><br/></p></body></html>", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Quantity</span></p><p align=\"right\"><br/></p></body></html>", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Bag Type</span></p></body></html>", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:700;\">EDIT FINISHED PRODUCT</span></p></body></html>", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">No. of Defectives</span></p><p align=\"right\"><br/></p></body></html>", None))
        self.Archive_finished_product.setText(QCoreApplication.translate("MainWindow", u"Archive", None))
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Material Name</span></p></body></html>", None))
        self.add_material_type.setText("")
        self.label_67.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Material Safety Stock</span></p></body></html>", None))
        self.label_68.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Supplier Name</span></p></body></html>", None))
        self.save_add_raw.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.label_72.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:700;\">ADD RAW MATERIAL</span></p></body></html>", None))
        self.label_69.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Material Cost</span></p></body></html>", None))
        self.cancel_add_raw.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.label_71.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Material Stock</span></p></body></html>", None))
        self.label_70.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Material Type</span></p></body></html>", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Material Name</span></p></body></html>", None))
        self.cancel_edit_raw.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.archive_raw.setText(QCoreApplication.translate("MainWindow", u"Archive", None))
        self.update_edit_raw.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Material Cost</span></p></body></html>", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Material Type</span></p></body></html>", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Material Stock</span></p></body></html>", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:700;\">EDIT RAW MATERIAL</span></p></body></html>", None))
        self.label_63.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Material Safety Stock</span></p></body></html>", None))
        self.Edit_material_type.setText("")
        self.label_64.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-weight:700;\">Supplier Name</span></p></body></html>", None))
        self.label_75.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700;\">Transaction History</span></p></body></html>", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Poppins Light'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI';\">This program is the production management system for Rexie Maris Bag Enterprise.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI';\">The program contains the following features as seen in the menu navigation bar in the left</span></p"
                        ">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI'; font-weight:700;\">\u2022 Dashboard</span><span style=\" font-family:'Segoe UI';\"> is the overall view of the general production state</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI'; font-weight:700;\">\u2022 Production Tracking </span><span style=\" font-family:'Segoe UI';\">contains the database of the current production status and the </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI';\">corresponding buttons for its management</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI"
                        "'; font-weight:700;\">\u2022 Scheduling </span><span style=\" font-family:'Segoe UI';\">contains the deadlines and goals that are needed to be met</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI'; font-weight:700;\">\u2022 Inventory Management </span><span style=\" font-family:'Segoe UI';\">contains the information about the raw materials for production</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI'; font-weight:700;\">\u2022 Reports </span><span style=\" font-family:'Segoe UI';\">module contains the overview of the production process and inventory</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI'; font-weight:700;\">\u2022 Transaction Histo"
                        "ry </span><span style=\" font-family:'Segoe UI';\">contains the records of data input in the system</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI'; font-weight:700;\">\u2022 Help </span><span style=\" font-family:'Segoe UI';\">contains the general information about the system</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI'; font-weight:700;\">\u2022 Maintenance </span><span style=\" font-family:'Segoe UI';\">contains the current system version and will serve as the portal for future updates.</span></p></body></html>", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Help</p></body></html>", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Instructions", None))
        self.maintenance_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Maintenance</p></body></html>", None))
        self.version_label.setText(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Poppins Light'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI';\">Current Version:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI'; font-size:24pt; font-weight:700;\">1.0.0</span></p></body></html>", None))
        self.update_button.setText(QCoreApplication.translate("MainWindow", u"Update", None))
        self.backup_button.setText(QCoreApplication.translate("MainWindow", u"Backup", None))
        self.restore_button.setText(QCoreApplication.translate("MainWindow", u"Restore", None))
        self.textEdit.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Input details here</p></body></html>", None))
        self.label_128.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-weight:700;\">Report a Bug</span></p></body></html>", None))
        self.welcome_label_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-style:italic;\">Production</span></p></body></html>", None))
        self.add_order_button.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Client Name</span></p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Bag Type</span></p></body></html>", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Order Quantity</span></p><p><br/></p></body></html>", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Deadline</span></p><p><br/></p></body></html>", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Notes</span></p></body></html>", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Priority Assignment</span></p><p><br/></p></body></html>", None))
        self.cancel_add_order.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.save_add_order.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">ADD ORDER</span></p></body></html>", None))
        self.edit_cancel_button.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.edit_save_button.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Priority Assignment</span></p><p><br/></p></body></html>", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Client Name</span></p></body></html>", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Order Quantity</span></p><p><br/></p></body></html>", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Deadline</span></p><p><br/></p></body></html>", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Notes</span></p></body></html>", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">EDIT ORDER</span></p></body></html>", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Bag Type</span></p></body></html>", None))
        self.void_order.setText(QCoreApplication.translate("MainWindow", u"Void Order", None))
        self.daily_calendar.setText(QCoreApplication.translate("MainWindow", u"Daily", None))
        self.weekly_calendar.setText(QCoreApplication.translate("MainWindow", u"Weekly", None))
        self.label_73.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700;\">This week's Deadlines</span></p></body></html>", None))
        self.return_calendar.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.edit_weekly.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.save_weekly.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.label_74.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700;\">This day's Deadlines</span></p></body></html>", None))
        self.return_calendar_2.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.save_daily.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.edit_daily.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>About</p></body></html>", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Poppins Light'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI';\">This application is the production management system for the Rexie Maris Bag Enterprise.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI';\">Thiswas developed by the students of Technological Institute of the Philippines Quezon City:"
                        "</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI';\">\u2022 Amorato, Charlize</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI';\">\u2022 Pasquil, Kristan Jay</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI';\">\u2022 Roxas, Marx Gabriel</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Segoe UI';\">As a fulfillment for the requirements of the Software Engineering class under the Computer </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span st"
                        "yle=\" font-family:'Segoe UI';\">Science degree program curriculum.</span></p></body></html>", None))
        self.maintenance_label_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Reports</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.prod_report_btn.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.prod_report_btn.setText(QCoreApplication.translate("MainWindow", u"Generate Production Report", None))
#if QT_CONFIG(tooltip)
        self.inventory_report_btn.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.inventory_report_btn.setText(QCoreApplication.translate("MainWindow", u"Generate Inventory Report", None))
#if QT_CONFIG(tooltip)
        self.stocks_report_btn.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.stocks_report_btn.setText(QCoreApplication.translate("MainWindow", u"Generate Stocks Report", None))
#if QT_CONFIG(tooltip)
        self.sales_report_btn.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.sales_report_btn.setText(QCoreApplication.translate("MainWindow", u"Generate Sales Report", None))
        self.dash_button.setText(QCoreApplication.translate("MainWindow", u"Dashboard", None))
        self.prod_button.setText(QCoreApplication.translate("MainWindow", u"Production Tracking", None))
        self.sched_button.setText(QCoreApplication.translate("MainWindow", u"Scheduling", None))
        self.invent_button.setText(QCoreApplication.translate("MainWindow", u"Inventory Management", None))
        self.rep_button.setText(QCoreApplication.translate("MainWindow", u"Reports", None))
        self.transac_button.setText(QCoreApplication.translate("MainWindow", u"Transaction History", None))
        self.help_button.setText(QCoreApplication.translate("MainWindow", u"Help", None))
        self.about_button.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.maintenance_button.setText(QCoreApplication.translate("MainWindow", u"Maintenance", None))
        self.username_id.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\">RXA1</p></body></html>", None))
    # retranslateUi

